/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatLayoutRouteImport } from './routes/_chatLayout'
import { Route as ChatLayoutIndexRouteImport } from './routes/_chatLayout.index'
import { Route as ChatLayoutChatThreadIdRouteImport } from './routes/_chatLayout.chat.$threadId'

const ChatLayoutRoute = ChatLayoutRouteImport.update({
  id: '/_chatLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLayoutIndexRoute = ChatLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatLayoutRoute,
} as any)
const ChatLayoutChatThreadIdRoute = ChatLayoutChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ChatLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '': typeof ChatLayoutRouteWithChildren
  '/': typeof ChatLayoutIndexRoute
  '/chat/$threadId': typeof ChatLayoutChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatLayoutIndexRoute
  '/chat/$threadId': typeof ChatLayoutChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chatLayout': typeof ChatLayoutRouteWithChildren
  '/_chatLayout/': typeof ChatLayoutIndexRoute
  '/_chatLayout/chat/$threadId': typeof ChatLayoutChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$threadId'
  id:
    | '__root__'
    | '/_chatLayout'
    | '/_chatLayout/'
    | '/_chatLayout/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chatLayout': {
      id: '/_chatLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chatLayout/': {
      id: '/_chatLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatLayoutIndexRouteImport
      parentRoute: typeof ChatLayoutRoute
    }
    '/_chatLayout/chat/$threadId': {
      id: '/_chatLayout/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatLayoutChatThreadIdRouteImport
      parentRoute: typeof ChatLayoutRoute
    }
  }
}

interface ChatLayoutRouteChildren {
  ChatLayoutIndexRoute: typeof ChatLayoutIndexRoute
  ChatLayoutChatThreadIdRoute: typeof ChatLayoutChatThreadIdRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatLayoutIndexRoute: ChatLayoutIndexRoute,
  ChatLayoutChatThreadIdRoute: ChatLayoutChatThreadIdRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(
  ChatLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
